chen2573/classy-schedule-desktop

- src/App.js
- src/components/AddSolution.js
- src/components/Menubar.js
- src/components/SolutionPage.js
I updated App.js, Menubar.js, solution.js, and added an AddSolution.js to show what our generate solution may look like.
> Added add solution page

- src/components/CourseAddPage.js
- src/components/LabAddPage.js
- src/components/RoomAddPage.js
Adjusted Joe's input code for the other pages
> Input Checking Code in Remaining Add Pages

- src/components/CourseAddPage.js
- src/components/LabAddPage.js
- src/components/ProfessorAddPage.js
- src/components/RoomAddPage.js
Updated entry field id style and selected option color
> Updated entry field id style and selected option color

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/components/SideNavigation.js
- src/services/databaseServices/UIDatabaseService.js
This PR adds wrapper functions for Professor DB functions.
> Adding full DB functionality to Professors.

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/services/databaseServices/UIDatabaseService.js
This PR adds additional functionality for courses.
> Adding DB functionality for Courses.

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/components/RoomAddPage.js
- src/services/databaseServices/UIDatabaseService.js
This PR adds full functionality with the DB for the Rooms feature.
> Adding complete DB functionality for Rooms.

- package.json
- public/electron.js
This PR creates release v0.3.0.
> Fixing issue that was causing release to crash.

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/components/AddSolution.js
- src/services/databaseServices/UIDatabaseService.js
This PR refactors App.js so that functions for the same feature are grouped together. This PR also fixes course delete to reflect changes made to the database API.
> Refactoring App.js and fixing course delete functionality.

- src/components/schedulePages/AddSolution.js
Refactoring AddSolution so that we will be able to hold state.
> Refactoring AddSolution so that we will be able to hold state.

- public/electron.js
- src/App.js
- src/components/addPages/ProfessorAddPage.js
- src/components/schedulePages/AddSolution.js
- src/services/databaseServices/UIDatabaseService.js
This PR fixes a bug that was occurring in the select screen. This PR also adds the professor's last name to DB calls with professor.
> Fixing bug with Select screen and adding DB call for Prof last name.

- src/App.js
- src/components/addPages/LabAddPage.js
- src/components/addPages/ProfessorAddPage.js
- src/components/schedulePages/AddSolution.js
- src/services/algorithmServices/mainAlgorithmService.js
This PR adds the ability for AddSolution.js to save the selected state. This PR also adds logic to take the saved state and create a json from it.
> Saving selected state and converting to json.

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/components/addPages/ProfessorAddPage.js
- src/services/databaseServices/UIDatabaseService.js
This PR adds DB functionality to updating. There is still a bug where the update does not show up until the app is refreshed.
> Adding DB functionality to Prof update.

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/components/addPages/CourseAddPage.js
- src/services/databaseServices/UIDatabaseService.js
The PR fixes async issues that were occurring when a user tried to delete a course they just added. This PR also removes 'CourseId' property from Course.
> Fixing async add/delete bugs.

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/components/addPages/CourseAddPage.js
- src/components/addPages/ProfessorAddPage.js
- src/services/databaseServices/UIDatabaseService.js
This PR adds updated functionality to courses. This PR also fixes a few bugs in professor page.
> Adding update functionality to Course.

- src/components/Menubar.js
- src/components/addPages/CourseAddPage.js
I removed Lab from the menu bar but didn't delete the component or the related code in App.js yet. Associated Course is currently commented out on the form so just a checkbox for lab will show up right now.
> Putting Lab into Course Page

- public/electron.js
- public/services/databaseService.js
- public/views/login/login.css
- public/views/newPlan/plan.css
- public/views/newPlan/plan.html
- public/views/newPlan/plan.js
- src/components/schedulePages/SolutionPage.js
- src/services/databaseServices/saveSolutionService.js
This PR adds a modal window to create a plan. The PR also adds the DB functionality to this modal window.
> Adding save schedule dialogue box.

- public/electron.js
- src/App.js
- src/services/algorithmServices/mainAlgorithmService.js
- src/services/databaseServices/UIDatabaseService.js
This PR adds a cantor pairing function to map department and course number to a singular number to use as id.
> Adding cantorPairing function to use as id for Courses.

- public/electron.js
- public/services/databaseService.js
- src/App.js
- src/components/addPages/RoomAddPage.js
- src/components/schedulePages/AddSolution.js
- src/services/algorithmServices/mainAlgorithmService.js
- src/services/databaseServices/UIDatabaseService.js
This PR adds room update functionality to UI and DB.
> Room update DB functionality.

- src/App.js
- src/components/addPages/CourseAddPage.js
- src/components/schedulePages/AddSolution.js
Adding initial support for labs in courses.
> Adding support for labs in courses.

- .gitignore
- public/electron.js
- public/preload.js
- public/services/mainDBService.js
- src/App.js
- src/components/schedulePages/SolutionDashboard.js
- src/components/schedulePages/UpdateSolution.js
- src/services/databaseServices/solutionDBService.js
This PR adds the base functionality for retrieving plans from DB.
> Adding base functionality to retrieve Plan from DB.

- public/electron.js
- src/components/schedulePages/AddSolution.js
- src/components/schedulePages/SolutionPage.js
- src/components/schedulePages/UpdateSolution.js
- src/services/algorithmServices/mainAlgorithmService.js
This PR adds incomplete functionality to the settings button. Still need to fix some bugs. This PR also adds a loading icon, which needs to still be styled.
> Adding backend functionality to settings button.

- src/assets/styles/Solution.css
- src/components/schedulePages/AddSolution.js
- src/components/schedulePages/SolutionPage.js
This PR adds edit capability to the Algorithm solution page. We are now able to enter into an 'edit' mode where a user can add and delete sections.
> Adding manual edit functionality to Algorithm Solution page.

- src/App.js
- src/assets/styles/AddPages.css
- src/components/schedulePages/CreateSolutionPage.js
- src/components/schedulePages/SolutionDashboard.js
This PR adds a new way to create schedules manually.
> Adding manual schedule entry page.

- public/electron.js
- public/preload.js
- public/services/mainDBService.js
- src/App.js
- src/components/schedulePages/CreateSolutionPage.js
- src/components/schedulePages/SolutionPage.js
- src/components/schedulePages/UpdateSolution.js
- src/components/schedulePages/ViewSolution.js
- src/services/databaseServices/solutionDBService.js
This PR includes many changes. Updated the way we store schedule data to the database reflecting the new DB schema. This PR also adds a ViewSolution page with edit functionality. We now have three solution pages: One for Viewing a created schedule, One for creating a schedule from scratch, and one for the schedule our algorithm generates. This PR also adds time functionality to our application. Time is now being pulled from the database.
> Adding View Solution and updating DB storage.

- public/electron.js
- public/preload.js
- public/services/mainDBService.js
- public/views/updatePlan/plan.css
- public/views/updatePlan/plan.html
- public/views/updatePlan/plan.js
- src/components/schedulePages/CreateSolutionPage.js
- src/components/schedulePages/SolutionDashboard.js
- src/components/schedulePages/SolutionPage.js
- src/components/schedulePages/ViewSolution.js
- src/services/databaseServices/solutionDBService.js
This PR adds update functionality when viewing a schedule.
> Adding Update functionality to View Solution page.

- public/electron.js
- public/services/mainDBService.js
- src/components/schedulePages/ViewSolution.js
- src/services/databaseServices/solutionDBService.js
This PR adds delete functionality to the ViewSchedule page.
> Adding delete functionality to ViewSolution.

- src/App.js
- src/components/schedulePages/SolutionDashboard.js
This PR makes sure that Solution Dashboard is up to date on load. A similar change should be done to all pages.
> Refreshing the Solution Dashboard on load.

- public/electron.js
- src/assets/styles/AddPages.css
- src/components/addPages/CourseAddPage.js
- src/components/addPages/ProfessorAddPage.js
- src/components/addPages/RoomAddPage.js
Reformatted Add Pages
Restricted valid inputs for # of sections
> Formatting and Input Restriction

- src/components/schedulePages/AddSolution.js
Checks to make sure there is a high enough total teach load for section and labs. Need to do #rooms * #times compared to number of sections and labs. Possibly more constraints.
> Partial Completion of Input Check for schedule creation

- public/electron.js
- public/services/mainDBService.js
- public/views/login/login.js
- public/views/newAccount/newAccount.html
- public/views/newAccount/newAccount.js
This PR adds DB support to the create account page. This won't work for now, because of some authorization, but it should be good to go.
> Adding user creation DB support at login

- public/electron.js
- public/services/mainDBService.js
- src/App.js
- src/components/schedulePages/ViewSolution.js
- src/services/databaseServices/appDBService.js
- src/services/databaseServices/solutionDBService.js
This PR updates all the places where we had to calculate the Class id by pairing the program id and course number.
> Restructuring Class state and references to use new id.

- src/components/schedulePages/CreateSolutionPage.js
- src/components/schedulePages/ViewSolution.js
- src/services/databaseServices/solutionDBService.js
This PR adds basic constraints to the solution pages.
> Adding constraints to Solution pages.

- src/components/schedulePages/CreateSolutionPage.js
- src/components/schedulePages/SolutionPage.js
- src/components/schedulePages/ViewSolution.js
This PR adds section calculation back into our solution pages.
> Adding section calculation back in.

- src/components/addPages/CourseAddPage.js
This PR removes unused data in the Course add page.
> Commenting out unused data input in Course Add page.

- src/App.js
- src/components/addPages/CourseAddPage.js
- src/components/addPages/RoomAddPage.js
This PR removes unneeded state variables for courses, rooms, and professors.
> Removing state variable that are unneeded

- public/electron.js
- public/preload.js
- public/services/mainDBService.js
- src/App.js
- src/components/addPages/ProfessorAddPage.js
This PR pulls teacher preference data from DB and sets the Professors state with teacher preference data that can be used. The only teach preferences we are supporting now are can_teach and want_teach.
> Adding teaching preferences.

- src/App.js
- src/components/addPages/CourseAddPage.js
- src/components/addPages/ProfessorAddPage.js
changed professor_id to prof_id
removed time_block refrences
lab state should be tracked
> Tracked lab state

- src/App.js
- src/components/addPages/ProfessorAddPage.js
- src/utils/appPreferencesService.js
This PR fixes the async bug that was occurring when pulling and mapping professor preferences.
> Fixing professor preferences bug.

- src/utils/appPreferencesService.js
The PR fixes another async bug that was occurring sometimes effecting professors.
> Additional fixes for teacher prefs bug.

- src/services/databaseServices/appDBService.js
This PR adds a small fix to the professor edit functionality.
> Fixing professor edit bug.

- src/App.js
This PR separates our courses state into allCourses, courses, and labs, so we can work with them individually.
> Separating out courses into allCourses, courses, and labs.

- src/components/schedulePages/AddSolution.js
This PR adds more basic constraint logic to the AddSolution page before sending data to the algorithm.
> Adding more constraint logic to AddSolution.js.

- package.json
- public/electron.js
- src/App.js
- src/utils/appPreferencesService.js
This PR adds some important changes so that we can use our executable in the built version.
> Making changes for release v1.0.1.
